apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: combined-scaledobject
spec:
  scaleTargetRef:
    name: conversao-distancia
  minReplicaCount: 1
  maxReplicaCount: 10
  triggers:
    - type: cpu
      metadata:
        type: Utilization
        value: "50"
    - type: memory
      metadata:
        type: Utilization
        value: "20"