apiVersion: apps/v1
kind: Deployment
metadata:
    name: distance-converter
spec:
    replicas: 6
    selector:
        matchLabels:
            app: distance-converter
    template:
        metadata:
            labels:
                app: distance-converter
        spec:
            containers:
            - name: distance-converter
              image: felipepanegalli/distance-conversor:latest
              ports:
              - containerPort: 5000
---

apiVersion: v1
kind: Service
metadata:
    name: distance-converter
spec:
    selector:
        app: distance-converter
    ports:
    - port: 8070
      targetPort: 5000
      nodePort: 30000
    type: NodePort
